version: '3.8'

services:
  babbel-ai-academy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: babbel-ai-academy
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - babbel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: babbel-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - babbel-ai-academy
    networks:
      - babbel-network
    restart: unless-stopped
    profiles:
      - production

networks:
  babbel-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
