version: '3.8'

services:
  # Frontend Development Server
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - /app/node_modules
    depends_on:
      - backend-dev
    networks:
      - babbel-dev-network
    container_name: babbel-frontend-dev

  # Backend Development Server
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app:ro
      - ./backend/src/content:/app/src/content
    networks:
      - babbel-dev-network
    container_name: babbel-backend-dev
    command: ["python", "app.py"]

networks:
  babbel-dev-network:
    driver: bridge
    name: babbel-ai-academy-dev
